
import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

export async function GET(
    request: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    const { id } = await params;
    const workspaceId = id;

    try {
        const workspace = await db.workspace.findUnique({
            where: { id: workspaceId },
            include: {
                modules: {
                    orderBy: { index: 'asc' }
                }
            }
        });

        if (!workspace) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 });

        let markdown = `# Study Guide: ${workspace.originalName} \n\n`;
        markdown += `Generated by PDF Learning Assistant\n\n`;

        workspace.modules.forEach(mod => {
            markdown += `## Module ${mod.index}: ${mod.title} \n\n`;
            markdown += `### Summary\n${mod.summary} \n\n`;

            const terms = JSON.parse(mod.keyTerms);
            markdown += `### Key Terms\n`;
            terms.forEach((term: string) => {
                markdown += `- ${term} \n`;
            });
            markdown += `\n`;

            const citations = JSON.parse(mod.citations);
            markdown += `* Reference Pages: ${citations.join(', ')}*\n\n`;
            markdown += `-- -\n\n`;
        });

        return new NextResponse(markdown, {
            headers: {
                'Content-Type': 'text/markdown',
                'Content-Disposition': `attachment; filename = "${workspace.filename.split('.')[0]}_study_guide.md"`,
            },
        });

    } catch (error) {
        return NextResponse.json({ error: 'Export failed' }, { status: 500 });
    }
}
